name: Docker

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
    - dev
    - main
  tags: ["*"]

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality.yaml

  docker:
    needs: quality
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # https://github.com/actions/checkout/issues/1418
      with:
        ref: "${{ github.head_ref || github.ref }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ndfeb/local-todo
        tags: |
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=ref,event=branch
          type=sha,prefix={{branch}}-

    - run: echo "steps.meta.outputs.tags = ${{ steps.meta.outputs.tags }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
