name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  BASE_PATH: /local-todo/

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality.yaml

  build:
    name: Build
    needs: quality
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout/issues/1418
    - uses: actions/checkout@v4
      with:
        ref: "${{ github.head_ref || github.ref }}"

    - uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'

    - name: Setup
      run: npm ci

    - name: Build
      run: npm run build

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
