name: Quality

on:
  workflow_dispatch:
  workflow_call:

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout/issues/1418
    - uses: actions/checkout@v4
      with:
        ref: "${{ github.head_ref || github.ref }}"

    - uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'

    - name: Setup
      run: npm ci

    - name: Lint
      run: npm run lint
